export const MetaData = {
    "CO PO Map": {
        // _id: "pk",
        "fk_Subject Code": "fk_Subject",
        CO: "str",
        PO: "str",
        Value: "str",
    },
    Class: {
        // _id: "pk",
        "fk_Department ID": "fk_Department",
        Semester: "int",
        Section: "str",
    },
    "Class Allocation": {
        // _id: "pk",
        "fk_Class ID": "fk_Class",
        fk_USN: "fk_Student",
    },
    Department: {
        // _id: "pk",
        "Department Name": "str",
        "fk_Hod ID": "fk_Teacher",
    },
    Marks: {
        // _id: "pk",
        fk_USN: "fk_Student",
        "fk_Subject Code": "fk_Subject",
        "obj_Marks Gained": "IA(CO(int))",
    },
    Student: {
        // _id: "pk",
        USN: "pk",
        "Student Name": "str",
        "fk_Department ID": "fk_Department",
    },
    Subject: {
        // _id: "pk",
        "Scheme Code": "str",
        "Subject Code": "pk",
        "Subject Name": "str",
        "Semester": "int",
        "Test Assignment Ratio": "int",
        "obj_Max Marks": "IA(CO())",
        "fk_Department ID": "fk_Department",
    },
    Teacher: {
        // _id: "pk",
        "Teacher Name": "str",
        Mail: "str_unique",
        Role: "str",
        "fk_Department ID": "fk_Department",
    },
    "Teacher Allocation": {
        // _id: "pk",
        "fk_Teacher ID": "fk_Teacher",
        "fk_Subject Code": "fk_Subject",
        "fk_Class ID": "fk_Class",
        "fk_Department ID": "fk_Department",
    },
};
